# Generated by Django 4.0.3 on 2022-05-03 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Credentials',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('like', models.IntegerField()),
                ('dislike', models.IntegerField()),
            ],
            options={
                'db_table': 'Like',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('price', models.FloatField()),
                ('imageid', models.CharField(max_length=255)),
                ('likeid', models.ForeignKey(db_column='likeid', on_delete=django.db.models.deletion.DO_NOTHING, to='base.like')),
            ],
            options={
                'db_table': 'Listing',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('Farmer', 'Farmer'), ('Vendor', 'Vendor'), ('Expert', 'Expert'), ('Admin', 'Admin')], max_length=6)),
                ('imageid', models.CharField(max_length=255)),
                ('credentials', models.ForeignKey(db_column='credentials', on_delete=django.db.models.deletion.DO_NOTHING, to='base.credentials')),
            ],
            options={
                'db_table': 'Profile',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('PENDING', 'PENDING'), ('FAILED', 'FAILED')], max_length=7)),
                ('amount', models.FloatField()),
                ('buyerid', models.ForeignKey(db_column='buyerid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='buyer_id', to='base.profile')),
                ('listingid', models.ForeignKey(db_column='listingid', on_delete=django.db.models.deletion.DO_NOTHING, to='base.listing')),
                ('sellerid', models.ForeignKey(db_column='sellerid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='seller_id', to='base.profile')),
            ],
            options={
                'db_table': 'Transaction',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('content', models.CharField(max_length=2000)),
                ('title', models.CharField(max_length=255)),
                ('likeid', models.ForeignKey(db_column='likeid', on_delete=django.db.models.deletion.DO_NOTHING, to='base.like')),
                ('profileid', models.ForeignKey(db_column='profileid', on_delete=django.db.models.deletion.DO_NOTHING, to='base.profile')),
            ],
            options={
                'db_table': 'Post',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='profileid',
            field=models.ForeignKey(db_column='profileid', on_delete=django.db.models.deletion.DO_NOTHING, to='base.profile'),
        ),
        migrations.CreateModel(
            name='Likeinfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('likes', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=3)),
                ('likeid', models.ForeignKey(db_column='likeid', on_delete=django.db.models.deletion.DO_NOTHING, to='base.like')),
                ('profileid', models.ForeignKey(db_column='profileid', on_delete=django.db.models.deletion.DO_NOTHING, to='base.profile')),
            ],
            options={
                'db_table': 'LikeInfo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('content', models.CharField(max_length=1000)),
                ('likeid', models.ForeignKey(db_column='likeid', on_delete=django.db.models.deletion.DO_NOTHING, to='base.like')),
                ('listingid', models.ForeignKey(blank=True, db_column='listingid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.listing')),
                ('postid', models.ForeignKey(blank=True, db_column='postid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.post')),
                ('profileid', models.ForeignKey(db_column='profileid', on_delete=django.db.models.deletion.DO_NOTHING, to='base.profile')),
            ],
            options={
                'db_table': 'Comment',
                'managed': True,
            },
        ),
    ]
