# Generated by Django 4.0.3 on 2022-05-03 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_comment_listingid_alter_comment_postid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='credentials',
        ),
        migrations.AddField(
            model_name='credentials',
            name='profileid',
            field=models.ForeignKey(db_column='profileid', null=True, on_delete=django.db.models.deletion.CASCADE, to='base.profile'),
        ),
    ]
