# Generated by Django 4.0.3 on 2022-05-03 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_profile_credentials_credentials_profileid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeinfo',
            name='likeid',
            field=models.ForeignKey(db_column='likeid', on_delete=django.db.models.deletion.CASCADE, to='base.like'),
        ),
    ]
