# Generated by Django 4.0.3 on 2022-05-03 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_likeinfo_likeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials',
            name='profileid',
            field=models.OneToOneField(db_column='profileid', null=True, on_delete=django.db.models.deletion.CASCADE, to='base.profile'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='likeid',
            field=models.OneToOneField(db_column='likeid', on_delete=django.db.models.deletion.CASCADE, to='base.like'),
        ),
        migrations.AlterField(
            model_name='post',
            name='likeid',
            field=models.OneToOneField(db_column='likeid', on_delete=django.db.models.deletion.CASCADE, to='base.like'),
        ),
    ]
