# Generated by Django 4.0.3 on 2022-05-04 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_credentials_profileid_alter_listing_likeid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='imageid',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
