# Generated by Django 4.0.3 on 2022-05-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_profile_imageid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
