# Generated by Django 4.0.3 on 2022-05-06 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_credentials_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 6, 7, 36, 26, 29739)),
        ),
        migrations.AlterField(
            model_name='likeinfo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 6, 7, 36, 26, 30535)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 6, 7, 36, 26, 30965)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 6, 7, 36, 26, 31316)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 6, 7, 36, 26, 31632)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 6, 7, 36, 26, 31879)),
        ),
    ]
