# Generated by Django 4.0.3 on 2022-05-06 07:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_comment_created_at_alter_likeinfo_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 6, 7, 38, 17, 644089, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='likeinfo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 6, 7, 38, 17, 645018, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 6, 7, 38, 17, 645313, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 6, 7, 38, 17, 645644, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 6, 7, 38, 17, 645948, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 6, 7, 38, 17, 646188, tzinfo=utc)),
        ),
    ]
