# Generated by Django 4.0.3 on 2022-05-09 06:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_credentials_profileid_profile_credid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('DELIVERED', 'DELIVERED'), ('IN_TRANSIT', 'IN_TRANSIT'), ('CANCELLED', 'CANCELLED')], max_length=11)),
                ('amount', models.FloatField()),
                ('buyerid', models.ForeignKey(db_column='buyerid', on_delete=django.db.models.deletion.CASCADE, related_name='buyer_id', to='base.profile')),
                ('listingid', models.ForeignKey(db_column='listingid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.listing')),
                ('sellerid', models.ForeignKey(db_column='sellerid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_id', to='base.profile')),
            ],
            options={
                'db_table': 'Order',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='credentials',
            name='profileid',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
