# Generated by Django 4.0.3 on 2022-05-09 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_rename_profileid_listing_sellerid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='sellerid',
        ),
    ]
