# Generated by Django 4.0.3 on 2022-05-09 07:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_remove_order_sellerid'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('role', models.CharField(choices=[('Farmer', 'Farmer'), ('Vendor', 'Vendor'), ('Expert', 'Expert'), ('Admin', 'Admin')], max_length=6)),
                ('reason', models.CharField(max_length=1000, null=True)),
                ('profileid', models.ForeignKey(db_column='profileid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.profile')),
            ],
            options={
                'db_table': 'RoleRequest',
                'managed': True,
            },
        ),
    ]
