# Generated by Django 4.0.3 on 2022-05-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_rolerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolerequest',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('PENDING', 'PENDING')], default='APPROVED', max_length=8),
            preserve_default=False,
        ),
    ]
