# Generated by Django 4.0.3 on 2022-05-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_rolerequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials',
            name='password',
            field=models.CharField(db_collation='utf8_bin', max_length=255),
        ),
        migrations.AlterField(
            model_name='credentials',
            name='username',
            field=models.CharField(db_collation='utf8_bin', max_length=255, unique=True),
        ),
    ]
