# Generated by Django 4.0.3 on 2022-05-10 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_credentials_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='imageid',
        ),
    ]
