# Generated by Django 4.0.3 on 2022-05-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_remove_profile_imageid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='imagename',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
