# Generated by Django 4.0.3 on 2022-05-10 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_profile_imagename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='imagename',
            new_name='profilepic',
        ),
    ]
