# Generated by Django 4.0.3 on 2022-05-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_rename_imagename_profile_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
