# Generated by Django 4.0.3 on 2022-05-12 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profilepic',
        ),
    ]
