# Generated by Django 4.0.3 on 2022-05-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_remove_profile_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profilepic',
            field=models.BooleanField(default=False),
        ),
    ]
