# Generated by Django 4.0.3 on 2022-05-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_profile_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolerequest',
            name='role',
            field=models.CharField(choices=[('Vendor', 'Vendor'), ('Expert', 'Expert'), ('Admin', 'Admin')], max_length=6),
        ),
    ]
