# Generated by Django 4.0.3 on 2022-05-12 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_alter_rolerequest_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolerequest',
            name='profileid',
            field=models.ForeignKey(db_column='profileid', null=True, on_delete=django.db.models.deletion.CASCADE, to='base.profile'),
        ),
    ]
