# Generated by Django 4.0.3 on 2022-05-13 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_rolerequest_profileid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='imageid',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='likeid',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likeid',
        ),
        migrations.AddField(
            model_name='like',
            name='listingid',
            field=models.OneToOneField(db_column='listingid', null=True, on_delete=django.db.models.deletion.CASCADE, to='base.listing'),
        ),
        migrations.AddField(
            model_name='like',
            name='postid',
            field=models.OneToOneField(db_column='postid', null=True, on_delete=django.db.models.deletion.CASCADE, to='base.post'),
        ),
    ]
