# Generated by Django 4.0.3 on 2022-05-13 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_remove_listing_imageid_remove_listing_likeid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='listingid',
            field=models.OneToOneField(db_column='listingid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like', to='base.listing'),
        ),
        migrations.AlterField(
            model_name='like',
            name='postid',
            field=models.OneToOneField(db_column='postid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like', to='base.post'),
        ),
    ]
