# Generated by Django 4.0.3 on 2022-05-13 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_alter_like_listingid_alter_like_postid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likeid',
        ),
        migrations.AddField(
            model_name='like',
            name='commentid',
            field=models.OneToOneField(db_column='commentid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like', to='base.comment'),
        ),
    ]
