# Generated by Django 4.0.3 on 2022-05-16 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_remove_comment_likeid_like_commentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='listingid',
            field=models.ForeignKey(blank=True, db_column='listingid', null=True, on_delete=django.db.models.deletion.CASCADE, to='base.listing'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='postid',
            field=models.ForeignKey(blank=True, db_column='postid', null=True, on_delete=django.db.models.deletion.CASCADE, to='base.post'),
        ),
    ]
