# Generated by Django 4.0.3 on 2022-05-16 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_alter_comment_listingid_alter_comment_postid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='sellerid',
            field=models.ForeignKey(db_column='profileid', on_delete=django.db.models.deletion.CASCADE, to='base.profile'),
        ),
    ]
