# Generated by Django 4.0.3 on 2022-05-17 06:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_alter_listing_sellerid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('listingid', models.ForeignKey(db_column='listingid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.listing')),
                ('profileid', models.ForeignKey(db_column='profileid', null=True, on_delete=django.db.models.deletion.CASCADE, to='base.profile')),
            ],
            options={
                'db_table': 'Cart',
                'managed': True,
            },
        ),
    ]
