# Generated by Django 4.0.3 on 2022-05-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='money',
            field=models.FloatField(default=0),
        ),
    ]
