# Generated by Django 4.0.3 on 2022-05-17 09:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_profile_money'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.CharField(max_length=1000)),
                ('profileid', models.ForeignKey(db_column='profileid', null=True, on_delete=django.db.models.deletion.CASCADE, to='base.profile')),
            ],
            options={
                'db_table': 'DeliveryAddress',
                'managed': True,
            },
        ),
    ]
