# Generated by Django 4.0.3 on 2022-05-17 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_deliveryaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
    ]
