# Generated by Django 4.0.3 on 2022-05-18 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_delete_deliveryaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
