# Generated by Django 4.0.3 on 2022-05-19 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_delete_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeinfo',
            name='likes',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO'), ('UNSURE', 'UNSURE')], max_length=6),
        ),
    ]
