# Generated by Django 4.0.3 on 2022-05-27 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_alter_likeinfo_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentid',
            field=models.ForeignKey(db_column='commentid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='base.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='listingid',
            field=models.ForeignKey(blank=True, db_column='listingid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='base.listing'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='postid',
            field=models.ForeignKey(blank=True, db_column='postid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='base.post'),
        ),
    ]
