# Generated by Django 4.0.3 on 2022-06-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_alter_comment_commentid_alter_comment_listingid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='Add a Bio', max_length=255, null=True),
        ),
    ]
