# Generated by Django 4.0.3 on 2022-07-08 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeinfo',
            name='likeid',
            field=models.ForeignKey(db_column='likeid', on_delete=django.db.models.deletion.CASCADE, related_name='likeinfo', to='base.like'),
        ),
    ]
