# Generated by Django 4.0.3 on 2022-07-08 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_alter_likeinfo_likeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='listingid',
            field=models.ForeignKey(blank=True, db_column='listingid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='base.listing'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='postid',
            field=models.ForeignKey(blank=True, db_column='postid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='base.post'),
        ),
    ]
