# Generated by Django 4.0.3 on 2022-07-28 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0044_alter_comment_listingid_alter_comment_postid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='credentialsid',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='credid',
            field=models.OneToOneField(db_column='credid', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='base.credentials'),
        ),
    ]
