# Generated by Django 4.0.3 on 2022-07-28 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_profile_credentialsid_alter_profile_credid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='credid',
        ),
    ]
