# Generated by Django 4.0.3 on 2022-07-28 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_remove_profile_credid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='credentialsid',
            new_name='credid',
        ),
    ]
